/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 46
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_pair_token1 = 1,
  sym_identifier = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_LBRACK = 5,
  anon_sym_COMMA = 6,
  anon_sym_RBRACK = 7,
  aux_sym_number_token1 = 8,
  aux_sym_string_token1 = 9,
  anon_sym_true = 10,
  anon_sym_false = 11,
  anon_sym_SLASH_SLASH = 12,
  anon_sym_POUND = 13,
  aux_sym__line_comment_token1 = 14,
  anon_sym_SLASH_STAR = 15,
  aux_sym__block_comment_token1 = 16,
  anon_sym_SLASH = 17,
  sym_document = 18,
  sym_pair = 19,
  sym__value = 20,
  sym__block_value = 21,
  sym_object = 22,
  sym_array = 23,
  sym_number = 24,
  sym_string = 25,
  sym_boolean = 26,
  sym_comment = 27,
  sym__line_comment = 28,
  sym__block_comment = 29,
  aux_sym_document_repeat1 = 30,
  aux_sym_array_repeat1 = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_pair_token1] = "pair_token1",
  [sym_identifier] = "identifier",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_SLASH_SLASH] = "//",
  [anon_sym_POUND] = "#",
  [aux_sym__line_comment_token1] = "_line_comment_token1",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym__block_comment_token1] = "_block_comment_token1",
  [anon_sym_SLASH] = "/",
  [sym_document] = "document",
  [sym_pair] = "pair",
  [sym__value] = "_value",
  [sym__block_value] = "_block_value",
  [sym_object] = "object",
  [sym_array] = "array",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_boolean] = "boolean",
  [sym_comment] = "comment",
  [sym__line_comment] = "_line_comment",
  [sym__block_comment] = "_block_comment",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_pair_token1] = aux_sym_pair_token1,
  [sym_identifier] = sym_identifier,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym__line_comment_token1] = aux_sym__line_comment_token1,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym__block_comment_token1] = aux_sym__block_comment_token1,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_document] = sym_document,
  [sym_pair] = sym_pair,
  [sym__value] = sym__value,
  [sym__block_value] = sym__block_value,
  [sym_object] = sym_object,
  [sym_array] = sym_array,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_boolean] = sym_boolean,
  [sym_comment] = sym_comment,
  [sym__line_comment] = sym__line_comment,
  [sym__block_comment] = sym__block_comment,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_pair_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__line_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__block_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym__block_value] = {
    .visible = false,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__line_comment] = {
    .visible = false,
    .named = true,
  },
  [sym__block_comment] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 3,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 17,
  [24] = 24,
  [25] = 20,
  [26] = 8,
  [27] = 18,
  [28] = 15,
  [29] = 16,
  [30] = 22,
  [31] = 9,
  [32] = 21,
  [33] = 33,
  [34] = 12,
  [35] = 13,
  [36] = 36,
  [37] = 14,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 41,
  [44] = 42,
  [45] = 40,
};

static const TSCharacterRange aux_sym_string_token1_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '#'}, {'%', '\''}, {'*', '+'}, {'-', 'Z'}, {'\\', '\\'}, {'^', 'z'},
  {'|', '|'}, {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      ADVANCE_MAP(
        '#', 54,
        ',', 28,
        '.', 17,
        '/', 60,
        '[', 27,
        ']', 29,
        'f', 10,
        't', 14,
        '{', 25,
        '}', 26,
        '+', 9,
        '-', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 35,
        '#', 55,
        ',', 28,
        '.', 45,
        '/', 36,
        '[', 27,
        ']', 29,
        'f', 38,
        't', 42,
        '{', 25,
        '+', 37,
        '-', 37,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '"' || '$' < lookahead) &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != '}') ADVANCE(47);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '"', 35,
        '.', 45,
        '[', 27,
        'f', 38,
        't', 42,
        '{', 25,
        '+', 37,
        '-', 37,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '(' &&
          lookahead != ')' &&
          (lookahead < '+' || '.' < lookahead) &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(47);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '\\') ADVANCE(18);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(57);
      if (lookahead == '/') ADVANCE(52);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(59);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(59);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '.') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 16:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 18:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 19:
      if (eof) ADVANCE(20);
      if (lookahead == '#') ADVANCE(54);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '}') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_pair_token1);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_pair_token1);
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_pair_token1);
      if (lookahead == '*') ADVANCE(59);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(47);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(47);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(47);
      if (lookahead == '\\') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '$' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == ',' ||
          ('[' <= lookahead && lookahead <= ']') ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(5);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(58);
      if (lookahead == '/') ADVANCE(53);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(47);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '.') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(47);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 'a') ADVANCE(41);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(47);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 'e') ADVANCE(49);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(47);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 'e') ADVANCE(51);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(47);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 'l') ADVANCE(43);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(47);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 'r') ADVANCE(44);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(47);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 's') ADVANCE(40);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(47);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 'u') ADVANCE(39);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(47);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(47);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '$' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == ',' ||
          lookahead == '[' ||
          lookahead == ']' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(5);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(35);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_true);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(47);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_false);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(47);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(47);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_POUND);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(47);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym__line_comment_token1);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(47);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym__block_comment_token1);
      if (lookahead == '*') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(8);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 19},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 19},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 19},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 19},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 19},
  [24] = {.lex_state = 19},
  [25] = {.lex_state = 19},
  [26] = {.lex_state = 19},
  [27] = {.lex_state = 19},
  [28] = {.lex_state = 19},
  [29] = {.lex_state = 19},
  [30] = {.lex_state = 19},
  [31] = {.lex_state = 19},
  [32] = {.lex_state = 19},
  [33] = {.lex_state = 19},
  [34] = {.lex_state = 19},
  [35] = {.lex_state = 19},
  [36] = {.lex_state = 19},
  [37] = {.lex_state = 19},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 7},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 7},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_pair_token1] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(39),
    [sym_pair] = STATE(24),
    [sym_comment] = STATE(24),
    [sym__line_comment] = STATE(32),
    [sym__block_comment] = STATE(32),
    [aux_sym_document_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_pair_token1] = ACTIONS(3),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SLASH_SLASH] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_SLASH_STAR] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym__value] = STATE(11),
    [sym_object] = STATE(11),
    [sym_array] = STATE(11),
    [sym_number] = STATE(11),
    [sym_string] = STATE(11),
    [sym_boolean] = STATE(11),
    [sym_comment] = STATE(3),
    [sym__line_comment] = STATE(21),
    [sym__block_comment] = STATE(21),
    [aux_sym_array_repeat1] = STATE(3),
    [aux_sym_pair_token1] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(17),
    [aux_sym_number_token1] = ACTIONS(19),
    [aux_sym_string_token1] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(25),
    [anon_sym_POUND] = ACTIONS(25),
    [anon_sym_SLASH_STAR] = ACTIONS(27),
  },
  [STATE(3)] = {
    [sym__value] = STATE(11),
    [sym_object] = STATE(11),
    [sym_array] = STATE(11),
    [sym_number] = STATE(11),
    [sym_string] = STATE(11),
    [sym_boolean] = STATE(11),
    [sym_comment] = STATE(4),
    [sym__line_comment] = STATE(21),
    [sym__block_comment] = STATE(21),
    [aux_sym_array_repeat1] = STATE(4),
    [aux_sym_pair_token1] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(29),
    [aux_sym_number_token1] = ACTIONS(19),
    [aux_sym_string_token1] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(25),
    [anon_sym_POUND] = ACTIONS(25),
    [anon_sym_SLASH_STAR] = ACTIONS(27),
  },
  [STATE(4)] = {
    [sym__value] = STATE(11),
    [sym_object] = STATE(11),
    [sym_array] = STATE(11),
    [sym_number] = STATE(11),
    [sym_string] = STATE(11),
    [sym_boolean] = STATE(11),
    [sym_comment] = STATE(4),
    [sym__line_comment] = STATE(21),
    [sym__block_comment] = STATE(21),
    [aux_sym_array_repeat1] = STATE(4),
    [aux_sym_pair_token1] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_LBRACK] = ACTIONS(34),
    [anon_sym_RBRACK] = ACTIONS(37),
    [aux_sym_number_token1] = ACTIONS(39),
    [aux_sym_string_token1] = ACTIONS(42),
    [anon_sym_true] = ACTIONS(45),
    [anon_sym_false] = ACTIONS(45),
    [anon_sym_SLASH_SLASH] = ACTIONS(48),
    [anon_sym_POUND] = ACTIONS(48),
    [anon_sym_SLASH_STAR] = ACTIONS(51),
  },
  [STATE(5)] = {
    [sym__value] = STATE(11),
    [sym_object] = STATE(11),
    [sym_array] = STATE(11),
    [sym_number] = STATE(11),
    [sym_string] = STATE(11),
    [sym_boolean] = STATE(11),
    [sym_comment] = STATE(6),
    [sym__line_comment] = STATE(21),
    [sym__block_comment] = STATE(21),
    [aux_sym_array_repeat1] = STATE(6),
    [aux_sym_pair_token1] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(54),
    [aux_sym_number_token1] = ACTIONS(19),
    [aux_sym_string_token1] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(25),
    [anon_sym_POUND] = ACTIONS(25),
    [anon_sym_SLASH_STAR] = ACTIONS(27),
  },
  [STATE(6)] = {
    [sym__value] = STATE(11),
    [sym_object] = STATE(11),
    [sym_array] = STATE(11),
    [sym_number] = STATE(11),
    [sym_string] = STATE(11),
    [sym_boolean] = STATE(11),
    [sym_comment] = STATE(4),
    [sym__line_comment] = STATE(21),
    [sym__block_comment] = STATE(21),
    [aux_sym_array_repeat1] = STATE(4),
    [aux_sym_pair_token1] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(56),
    [aux_sym_number_token1] = ACTIONS(19),
    [aux_sym_string_token1] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(25),
    [anon_sym_POUND] = ACTIONS(25),
    [anon_sym_SLASH_STAR] = ACTIONS(27),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_LBRACK,
    ACTIONS(62), 1,
      aux_sym_number_token1,
    ACTIONS(64), 1,
      aux_sym_string_token1,
    ACTIONS(66), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 7,
      sym__value,
      sym__block_value,
      sym_object,
      sym_array,
      sym_number,
      sym_string,
      sym_boolean,
  [29] = 3,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(68), 4,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    ACTIONS(70), 7,
      aux_sym_number_token1,
      aux_sym_string_token1,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [48] = 3,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(72), 4,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    ACTIONS(74), 7,
      aux_sym_number_token1,
      aux_sym_string_token1,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [67] = 7,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(84), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(76), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(81), 2,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
    STATE(32), 2,
      sym__line_comment,
      sym__block_comment,
    STATE(10), 3,
      sym_pair,
      sym_comment,
      aux_sym_document_repeat1,
  [94] = 4,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(89), 1,
      anon_sym_COMMA,
    ACTIONS(87), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(91), 7,
      aux_sym_number_token1,
      aux_sym_string_token1,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [115] = 3,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(93), 4,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    ACTIONS(95), 7,
      aux_sym_number_token1,
      aux_sym_string_token1,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [134] = 3,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(97), 4,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    ACTIONS(99), 7,
      aux_sym_number_token1,
      aux_sym_string_token1,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [153] = 3,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(101), 4,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    ACTIONS(103), 7,
      aux_sym_number_token1,
      aux_sym_string_token1,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [172] = 3,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(105), 4,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    ACTIONS(107), 7,
      aux_sym_number_token1,
      aux_sym_string_token1,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [191] = 3,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(109), 4,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    ACTIONS(111), 7,
      aux_sym_number_token1,
      aux_sym_string_token1,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [210] = 7,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(113), 1,
      anon_sym_RBRACE,
    ACTIONS(9), 2,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
    STATE(32), 2,
      sym__line_comment,
      sym__block_comment,
    STATE(20), 3,
      sym_pair,
      sym_comment,
      aux_sym_document_repeat1,
  [236] = 3,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(115), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(117), 7,
      aux_sym_number_token1,
      aux_sym_string_token1,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [254] = 3,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(37), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(119), 7,
      aux_sym_number_token1,
      aux_sym_string_token1,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [272] = 7,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    ACTIONS(9), 2,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
    STATE(32), 2,
      sym__line_comment,
      sym__block_comment,
    STATE(10), 3,
      sym_pair,
      sym_comment,
      aux_sym_document_repeat1,
  [298] = 3,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(123), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(125), 7,
      aux_sym_number_token1,
      aux_sym_string_token1,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [316] = 3,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(127), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(129), 7,
      aux_sym_number_token1,
      aux_sym_string_token1,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [334] = 7,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(131), 1,
      anon_sym_RBRACE,
    ACTIONS(9), 2,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
    STATE(32), 2,
      sym__line_comment,
      sym__block_comment,
    STATE(25), 3,
      sym_pair,
      sym_comment,
      aux_sym_document_repeat1,
  [360] = 7,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(133), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 2,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
    STATE(32), 2,
      sym__line_comment,
      sym__block_comment,
    STATE(10), 3,
      sym_pair,
      sym_comment,
      aux_sym_document_repeat1,
  [386] = 7,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(135), 1,
      anon_sym_RBRACE,
    ACTIONS(9), 2,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
    STATE(32), 2,
      sym__line_comment,
      sym__block_comment,
    STATE(10), 3,
      sym_pair,
      sym_comment,
      aux_sym_document_repeat1,
  [412] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(68), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [424] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(115), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [436] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(105), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [448] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(109), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [460] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(127), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [472] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(72), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [484] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(123), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [496] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(137), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [508] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(93), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [520] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(97), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [532] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(139), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [544] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(101), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [556] = 4,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_LBRACK,
    ACTIONS(141), 1,
      aux_sym_pair_token1,
    STATE(33), 3,
      sym__block_value,
      sym_object,
      sym_array,
  [571] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(143), 1,
      ts_builtin_sym_end,
  [578] = 2,
    ACTIONS(145), 1,
      aux_sym_pair_token1,
    ACTIONS(147), 1,
      aux_sym__block_comment_token1,
  [585] = 2,
    ACTIONS(145), 1,
      aux_sym_pair_token1,
    ACTIONS(149), 1,
      aux_sym__line_comment_token1,
  [592] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(151), 1,
      anon_sym_SLASH,
  [599] = 2,
    ACTIONS(145), 1,
      aux_sym_pair_token1,
    ACTIONS(153), 1,
      aux_sym__line_comment_token1,
  [606] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(155), 1,
      anon_sym_SLASH,
  [613] = 2,
    ACTIONS(145), 1,
      aux_sym_pair_token1,
    ACTIONS(157), 1,
      aux_sym__block_comment_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 29,
  [SMALL_STATE(9)] = 48,
  [SMALL_STATE(10)] = 67,
  [SMALL_STATE(11)] = 94,
  [SMALL_STATE(12)] = 115,
  [SMALL_STATE(13)] = 134,
  [SMALL_STATE(14)] = 153,
  [SMALL_STATE(15)] = 172,
  [SMALL_STATE(16)] = 191,
  [SMALL_STATE(17)] = 210,
  [SMALL_STATE(18)] = 236,
  [SMALL_STATE(19)] = 254,
  [SMALL_STATE(20)] = 272,
  [SMALL_STATE(21)] = 298,
  [SMALL_STATE(22)] = 316,
  [SMALL_STATE(23)] = 334,
  [SMALL_STATE(24)] = 360,
  [SMALL_STATE(25)] = 386,
  [SMALL_STATE(26)] = 412,
  [SMALL_STATE(27)] = 424,
  [SMALL_STATE(28)] = 436,
  [SMALL_STATE(29)] = 448,
  [SMALL_STATE(30)] = 460,
  [SMALL_STATE(31)] = 472,
  [SMALL_STATE(32)] = 484,
  [SMALL_STATE(33)] = 496,
  [SMALL_STATE(34)] = 508,
  [SMALL_STATE(35)] = 520,
  [SMALL_STATE(36)] = 532,
  [SMALL_STATE(37)] = 544,
  [SMALL_STATE(38)] = 556,
  [SMALL_STATE(39)] = 571,
  [SMALL_STATE(40)] = 578,
  [SMALL_STATE(41)] = 585,
  [SMALL_STATE(42)] = 592,
  [SMALL_STATE(43)] = 599,
  [SMALL_STATE(44)] = 606,
  [SMALL_STATE(45)] = 613,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line_comment, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line_comment, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_comment, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__block_comment, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [143] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gon(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gon",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
