/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 41
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_pair_token1 = 1,
  sym_identifier = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_LBRACK = 5,
  anon_sym_RBRACK = 6,
  aux_sym_number_token1 = 7,
  aux_sym_string_token1 = 8,
  anon_sym_true = 9,
  anon_sym_false = 10,
  anon_sym_SLASH_SLASH = 11,
  anon_sym_POUND = 12,
  aux_sym__line_comment_token1 = 13,
  anon_sym_SLASH_STAR = 14,
  aux_sym__block_comment_token1 = 15,
  sym_document = 16,
  sym_pair = 17,
  sym__value = 18,
  sym_object = 19,
  sym_array = 20,
  sym_number = 21,
  sym_string = 22,
  sym_boolean = 23,
  sym_comment = 24,
  sym__line_comment = 25,
  sym__block_comment = 26,
  aux_sym_document_repeat1 = 27,
  aux_sym_array_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_pair_token1] = "pair_token1",
  [sym_identifier] = "identifier",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_SLASH_SLASH] = "//",
  [anon_sym_POUND] = "#",
  [aux_sym__line_comment_token1] = "_line_comment_token1",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym__block_comment_token1] = "_block_comment_token1",
  [sym_document] = "document",
  [sym_pair] = "pair",
  [sym__value] = "_value",
  [sym_object] = "object",
  [sym_array] = "array",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_boolean] = "boolean",
  [sym_comment] = "comment",
  [sym__line_comment] = "_line_comment",
  [sym__block_comment] = "_block_comment",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_pair_token1] = aux_sym_pair_token1,
  [sym_identifier] = sym_identifier,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym__line_comment_token1] = aux_sym__line_comment_token1,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym__block_comment_token1] = aux_sym__block_comment_token1,
  [sym_document] = sym_document,
  [sym_pair] = sym_pair,
  [sym__value] = sym__value,
  [sym_object] = sym_object,
  [sym_array] = sym_array,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_boolean] = sym_boolean,
  [sym_comment] = sym_comment,
  [sym__line_comment] = sym__line_comment,
  [sym__block_comment] = sym__block_comment,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_pair_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__line_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__block_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__line_comment] = {
    .visible = false,
    .named = true,
  },
  [sym__block_comment] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 3,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 11,
  [23] = 9,
  [24] = 19,
  [25] = 13,
  [26] = 26,
  [27] = 12,
  [28] = 15,
  [29] = 16,
  [30] = 17,
  [31] = 18,
  [32] = 20,
  [33] = 21,
  [34] = 14,
  [35] = 35,
  [36] = 36,
  [37] = 36,
  [38] = 38,
  [39] = 38,
  [40] = 40,
};

static const TSCharacterRange aux_sym_string_token1_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '#'}, {'%', '\''}, {'*', '+'}, {'-', 'Z'}, {'\\', '\\'}, {'^', 'z'},
  {'|', '|'}, {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '"', 23,
        '#', 41,
        '.', 33,
        '/', 24,
        '[', 18,
        ']', 19,
        'f', 26,
        't', 30,
        '{', 16,
        '}', 17,
        '+', 25,
        '-', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (lookahead != 0 &&
          (lookahead < '"' || '$' < lookahead) &&
          lookahead != '(' &&
          lookahead != ')' &&
          (lookahead < '+' || '9' < lookahead)) ADVANCE(35);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 23,
        '.', 33,
        '[', 18,
        'f', 26,
        't', 30,
        '{', 16,
        '+', 25,
        '-', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '(' &&
          lookahead != ')' &&
          (lookahead < '+' || '.' < lookahead) &&
          lookahead != ']' &&
          lookahead != '}') ADVANCE(35);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(22);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(43);
      if (lookahead == '/') ADVANCE(38);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(45);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      if (lookahead == '#') ADVANCE(40);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '}') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_pair_token1);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_pair_token1);
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_pair_token1);
      if (lookahead == '*') ADVANCE(6);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(35);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(35);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(35);
      if (lookahead == '\\') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '$' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == ',' ||
          ('[' <= lookahead && lookahead <= ']') ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(4);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead == '/') ADVANCE(39);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(35);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '.') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(35);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 'a') ADVANCE(29);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(35);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 'e') ADVANCE(36);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(35);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 'e') ADVANCE(37);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(35);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 'l') ADVANCE(31);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(35);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 'r') ADVANCE(32);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(35);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 's') ADVANCE(28);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(35);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == 'u') ADVANCE(27);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(35);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '$' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == ',' ||
          lookahead == '[' ||
          lookahead == ']' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(4);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(23);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_true);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(35);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_false);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(35);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(35);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_POUND);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(35);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym__line_comment_token1);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if ((!eof && set_contains(aux_sym_string_token1_character_set_1, 10, lookahead))) ADVANCE(35);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym__block_comment_token1);
      if (lookahead == '*') ADVANCE(6);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 10},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 10},
  [9] = {.lex_state = 10},
  [10] = {.lex_state = 10},
  [11] = {.lex_state = 10},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 10},
  [23] = {.lex_state = 10},
  [24] = {.lex_state = 10},
  [25] = {.lex_state = 10},
  [26] = {.lex_state = 10},
  [27] = {.lex_state = 10},
  [28] = {.lex_state = 10},
  [29] = {.lex_state = 10},
  [30] = {.lex_state = 10},
  [31] = {.lex_state = 10},
  [32] = {.lex_state = 10},
  [33] = {.lex_state = 10},
  [34] = {.lex_state = 10},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_pair_token1] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_SLASH_STAR] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(35),
    [sym_pair] = STATE(10),
    [sym_comment] = STATE(10),
    [sym__line_comment] = STATE(27),
    [sym__block_comment] = STATE(27),
    [aux_sym_document_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_pair_token1] = ACTIONS(3),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SLASH_SLASH] = ACTIONS(9),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_SLASH_STAR] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym__value] = STATE(3),
    [sym_object] = STATE(3),
    [sym_array] = STATE(3),
    [sym_number] = STATE(3),
    [sym_string] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_comment] = STATE(3),
    [sym__line_comment] = STATE(12),
    [sym__block_comment] = STATE(12),
    [aux_sym_array_repeat1] = STATE(3),
    [aux_sym_pair_token1] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(17),
    [aux_sym_number_token1] = ACTIONS(19),
    [aux_sym_string_token1] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(25),
    [anon_sym_POUND] = ACTIONS(25),
    [anon_sym_SLASH_STAR] = ACTIONS(27),
  },
  [STATE(3)] = {
    [sym__value] = STATE(4),
    [sym_object] = STATE(4),
    [sym_array] = STATE(4),
    [sym_number] = STATE(4),
    [sym_string] = STATE(4),
    [sym_boolean] = STATE(4),
    [sym_comment] = STATE(4),
    [sym__line_comment] = STATE(12),
    [sym__block_comment] = STATE(12),
    [aux_sym_array_repeat1] = STATE(4),
    [aux_sym_pair_token1] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(29),
    [aux_sym_number_token1] = ACTIONS(19),
    [aux_sym_string_token1] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(25),
    [anon_sym_POUND] = ACTIONS(25),
    [anon_sym_SLASH_STAR] = ACTIONS(27),
  },
  [STATE(4)] = {
    [sym__value] = STATE(4),
    [sym_object] = STATE(4),
    [sym_array] = STATE(4),
    [sym_number] = STATE(4),
    [sym_string] = STATE(4),
    [sym_boolean] = STATE(4),
    [sym_comment] = STATE(4),
    [sym__line_comment] = STATE(12),
    [sym__block_comment] = STATE(12),
    [aux_sym_array_repeat1] = STATE(4),
    [aux_sym_pair_token1] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_LBRACK] = ACTIONS(34),
    [anon_sym_RBRACK] = ACTIONS(37),
    [aux_sym_number_token1] = ACTIONS(39),
    [aux_sym_string_token1] = ACTIONS(42),
    [anon_sym_true] = ACTIONS(45),
    [anon_sym_false] = ACTIONS(45),
    [anon_sym_SLASH_SLASH] = ACTIONS(48),
    [anon_sym_POUND] = ACTIONS(48),
    [anon_sym_SLASH_STAR] = ACTIONS(51),
  },
  [STATE(5)] = {
    [sym__value] = STATE(6),
    [sym_object] = STATE(6),
    [sym_array] = STATE(6),
    [sym_number] = STATE(6),
    [sym_string] = STATE(6),
    [sym_boolean] = STATE(6),
    [sym_comment] = STATE(6),
    [sym__line_comment] = STATE(12),
    [sym__block_comment] = STATE(12),
    [aux_sym_array_repeat1] = STATE(6),
    [aux_sym_pair_token1] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(54),
    [aux_sym_number_token1] = ACTIONS(19),
    [aux_sym_string_token1] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(25),
    [anon_sym_POUND] = ACTIONS(25),
    [anon_sym_SLASH_STAR] = ACTIONS(27),
  },
  [STATE(6)] = {
    [sym__value] = STATE(4),
    [sym_object] = STATE(4),
    [sym_array] = STATE(4),
    [sym_number] = STATE(4),
    [sym_string] = STATE(4),
    [sym_boolean] = STATE(4),
    [sym_comment] = STATE(4),
    [sym__line_comment] = STATE(12),
    [sym__block_comment] = STATE(12),
    [aux_sym_array_repeat1] = STATE(4),
    [aux_sym_pair_token1] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(56),
    [aux_sym_number_token1] = ACTIONS(19),
    [aux_sym_string_token1] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [anon_sym_SLASH_SLASH] = ACTIONS(25),
    [anon_sym_POUND] = ACTIONS(25),
    [anon_sym_SLASH_STAR] = ACTIONS(27),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(60), 1,
      anon_sym_LBRACK,
    ACTIONS(62), 1,
      aux_sym_number_token1,
    ACTIONS(64), 1,
      aux_sym_string_token1,
    ACTIONS(66), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(26), 6,
      sym__value,
      sym_object,
      sym_array,
      sym_number,
      sym_string,
      sym_boolean,
  [28] = 7,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(70), 1,
      sym_identifier,
    ACTIONS(76), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(68), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(73), 2,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
    STATE(27), 2,
      sym__line_comment,
      sym__block_comment,
    STATE(8), 3,
      sym_pair,
      sym_comment,
      aux_sym_document_repeat1,
  [55] = 7,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(79), 1,
      anon_sym_RBRACE,
    ACTIONS(9), 2,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
    STATE(27), 2,
      sym__line_comment,
      sym__block_comment,
    STATE(8), 3,
      sym_pair,
      sym_comment,
      aux_sym_document_repeat1,
  [81] = 7,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 2,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
    STATE(27), 2,
      sym__line_comment,
      sym__block_comment,
    STATE(8), 3,
      sym_pair,
      sym_comment,
      aux_sym_document_repeat1,
  [107] = 7,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(83), 1,
      anon_sym_RBRACE,
    ACTIONS(9), 2,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
    STATE(27), 2,
      sym__line_comment,
      sym__block_comment,
    STATE(9), 3,
      sym_pair,
      sym_comment,
      aux_sym_document_repeat1,
  [133] = 3,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(85), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(87), 7,
      aux_sym_number_token1,
      aux_sym_string_token1,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [151] = 3,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(89), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(91), 7,
      aux_sym_number_token1,
      aux_sym_string_token1,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [169] = 3,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(93), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(95), 7,
      aux_sym_number_token1,
      aux_sym_string_token1,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [187] = 3,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(97), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(99), 7,
      aux_sym_number_token1,
      aux_sym_string_token1,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [205] = 3,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(101), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(103), 7,
      aux_sym_number_token1,
      aux_sym_string_token1,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [223] = 3,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(105), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(107), 7,
      aux_sym_number_token1,
      aux_sym_string_token1,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [241] = 3,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(109), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(111), 7,
      aux_sym_number_token1,
      aux_sym_string_token1,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [259] = 3,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(113), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(115), 7,
      aux_sym_number_token1,
      aux_sym_string_token1,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [277] = 3,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(117), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(119), 7,
      aux_sym_number_token1,
      aux_sym_string_token1,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [295] = 3,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(121), 3,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(123), 7,
      aux_sym_number_token1,
      aux_sym_string_token1,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [313] = 7,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(125), 1,
      anon_sym_RBRACE,
    ACTIONS(9), 2,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
    STATE(27), 2,
      sym__line_comment,
      sym__block_comment,
    STATE(23), 3,
      sym_pair,
      sym_comment,
      aux_sym_document_repeat1,
  [339] = 7,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(127), 1,
      anon_sym_RBRACE,
    ACTIONS(9), 2,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
    STATE(27), 2,
      sym__line_comment,
      sym__block_comment,
    STATE(8), 3,
      sym_pair,
      sym_comment,
      aux_sym_document_repeat1,
  [365] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(113), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [377] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(89), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [389] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(129), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [401] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(85), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [413] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(97), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [425] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(101), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [437] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(105), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [449] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(109), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [461] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(117), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [473] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(121), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [485] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(93), 6,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_RBRACE,
      anon_sym_SLASH_SLASH,
      anon_sym_POUND,
      anon_sym_SLASH_STAR,
  [497] = 2,
    ACTIONS(3), 1,
      aux_sym_pair_token1,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
  [504] = 2,
    ACTIONS(133), 1,
      aux_sym_pair_token1,
    ACTIONS(135), 1,
      aux_sym__line_comment_token1,
  [511] = 2,
    ACTIONS(133), 1,
      aux_sym_pair_token1,
    ACTIONS(137), 1,
      aux_sym__line_comment_token1,
  [518] = 2,
    ACTIONS(133), 1,
      aux_sym_pair_token1,
    ACTIONS(139), 1,
      aux_sym__block_comment_token1,
  [525] = 2,
    ACTIONS(133), 1,
      aux_sym_pair_token1,
    ACTIONS(141), 1,
      aux_sym__block_comment_token1,
  [532] = 1,
    ACTIONS(143), 1,
      aux_sym_pair_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 28,
  [SMALL_STATE(9)] = 55,
  [SMALL_STATE(10)] = 81,
  [SMALL_STATE(11)] = 107,
  [SMALL_STATE(12)] = 133,
  [SMALL_STATE(13)] = 151,
  [SMALL_STATE(14)] = 169,
  [SMALL_STATE(15)] = 187,
  [SMALL_STATE(16)] = 205,
  [SMALL_STATE(17)] = 223,
  [SMALL_STATE(18)] = 241,
  [SMALL_STATE(19)] = 259,
  [SMALL_STATE(20)] = 277,
  [SMALL_STATE(21)] = 295,
  [SMALL_STATE(22)] = 313,
  [SMALL_STATE(23)] = 339,
  [SMALL_STATE(24)] = 365,
  [SMALL_STATE(25)] = 377,
  [SMALL_STATE(26)] = 389,
  [SMALL_STATE(27)] = 401,
  [SMALL_STATE(28)] = 413,
  [SMALL_STATE(29)] = 425,
  [SMALL_STATE(30)] = 437,
  [SMALL_STATE(31)] = 449,
  [SMALL_STATE(32)] = 461,
  [SMALL_STATE(33)] = 473,
  [SMALL_STATE(34)] = 485,
  [SMALL_STATE(35)] = 497,
  [SMALL_STATE(36)] = 504,
  [SMALL_STATE(37)] = 511,
  [SMALL_STATE(38)] = 518,
  [SMALL_STATE(39)] = 525,
  [SMALL_STATE(40)] = 532,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line_comment, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line_comment, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_comment, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__block_comment, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gon(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gon",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
